name: Pipeline CI/CD FastAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar dependências
      run: |
        pip install -r requirements.txt
        pip install pytest httpx
        
    - name: Executar os Testes Unitários
      run: pytest test_main.py

  cd-delivery:
    name: Continuous Delivery
    needs: ci-integration
    runs-on: ubuntu-latest
    steps:
    - name: Preparando Imagem Docker
      run: echo "Simulando push para o DockerHub..."